apiVersion: v1
kind: Service
metadata:
  name: my-app
spec:
  type: NodePort
  ports:
    - name: my-app
      port: 80
      targetPort: 3000
      protocol: TCP
  selector:
    app: my-app

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: my-app
        app: my-app
    spec:
      containers:
        - name: my-app
          image: my-app:v5
          ports:
            - name: main
              containerPort: 3000
              protocol: TCP